module.exports = [{
    name: 'Playa del Carmen',
    img: 'https://images.pexels.com/photos/12168652/pexels-photo-12168652.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: "Costal resourt town along the Caribbean shoreline",
    hotels: 'Hyatt',
    attractions: 'Mostly beaches',
    date: '1/30',
    travelPlan: 'Go to the beach',
},{
    name: 'Aruba',
    img: 'https://i.imgur.com/94oOjcw.png',
    description: 'Island in the southern Caribbean',
    hotels: 'Marriott Renaissance ',
    attractions: 'Flamingo Beach',
    date: '1/30',
    travelPlan: 'Go to the beach',
},
{
    name: 'South Korea',
    img: 'https://images.pexels.com/photos/2376712/pexels-photo-2376712.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Country located on southern half of Korean Peninsula, surrounded by Sea of Japan, Yellow Sea, and East China Sea ',
    hotels: 'Hyatt',
    attractions: 'Gyeongbokgung Palace',
    date: '1/30',
    travelPlan: 'Go to the Gyeongbokgung Palace',
},]